.\" Copyright (c) 2018-2019 Greg White <gkwhite@gmail.com>.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" $FreeBSD$
.\"
.Dd January 6, 2019
.Dt NPROC 1
.Os
.Sh NAME
.Nm nproc
.Nd return number of available processing units
.Sh SYNOPSIS
.Nm
.Op Fl a | Fl -all
.Op Fl i Ar N | Fl -ignore Ns = Ns Ar N
.Op Fl h | Fl -help
.Op Fl v | Fl -version
.Sh DESCRIPTION
The
.Nm
command displays the number of processors available
.Pp
The following options are available:
.Bl -tag -width Ds
.It Fl a , Fl Fl all
Print the number of available processors.  This ignores the OpenMP environment variables 
OMP_NUM_THREADS and OMP_THREAD_LIMIT.
.It Fl i Ar N , Fl Fl ignore Ns = Ns Ar N
Ignore the specified number of processors.  This happens after accounting for OpenMP
environment variables OMP_NUM_THREADS and OMP_THREAD_LIMIT.
.Nm
will always return at least 1
.It Fl h . Fl Fl help
Display help and exit
.It Fl v , Fl Fl version
Display version number and exit
.El
.Pp
.Nm
is a simple drop in replacement for the GNU coreutils nproc command often found in many operating systems.  It processes command line arguments, 
then calls the
.Xr sysctl 3
function.  To perform a similar function in the shell, use the following commands:
.Pp
.Dl $ sysctl hw.ncpu | awk '{print $2}'
.Pp
Like GNU coreutils nproc command, unless the -a or --all option is used, the OpenMP 
environment variables OMP_NUM_THREADS and OMP_THREAD_LIMIT provide a minumum and 
maximum value for the number of processors. However, there is always at least one processor.
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr sysctl 3 ,
.Xr sysctl 8
.Sh AUTHORS
.An -nosplit
The
.Nm
utility and this manual page was written by
.An Greg White Aq Mt gkwhite@gmail.com .
